::msgcat::mcmset en {
Abilities {Abilities}
back {Back}
Bend_Bars {Chance to bend bars}
Bonus_Spells_Lvl1 {Bonus spells of level 1}
Bonus_Spells_Lvl2 {Bonus spells of level 2}
Bonus_Spells_Lvl3 {Bonus spells of level 3}
Bonus_Spells_Lvl4 {Bonus spells of level 4}
Bonus_Spells_Lvl5 {Bonus spells of level 5}
Bonus_Spells_Lvl6 {Bonus spells of level 6}
Bonus_Spells_Lvl7 {Bonus spells of level 7}
Ch_To_Fail_Spell {Chance to fail spell cast}
Ch_To_Lrn_Spell  {Chance to learn spell}
Cha  {Charisma}
changes_after_restart {Changes will be applied after restarting of the program.}
Con  {Constitution}
copy {Copy}
create {Create}
cut {Cut}
Def_Adj {Defense modifier}
delete {Delete}
Dex  {Dextirity}
Dmg_Adj {Demage modifier}
exit {Exit}
female {Female}
file {File}
forward {Forward}
Gender {Gender}
Illusion_Immunity {Chance to reveal illusion}
Int  {Intellegence}
help {Help}
hero {Hero}
heroes {Heroes}
Hit_Prob {Hit probability}
HP_Adj {Health points modifier}
language {Language}
Loyality_Base {Basical servants loyality}
Magic_Save {Chance to save from spell}
Magical_Def_Adj {Magical defence modifier}
main_title {Roleplayer's assistant}
male {Male}
Max_Press {Maximal pressure allowed}
Max_Spells_Lvl {Maximal spells level}
Max_Henchmen {Maximal number of henchmen}
Missile_Atc_Adj {Missle attack modifier}
Name {Name}
Num_Of_Lang {Maximum number of learned languages}
open {Open}
Open_Doors {Chance to open locked door}
open_file_with {Open file with}
Open_Special_Doors {Chance to open special door}
paste {Paste}
Poison_Save {Chance to save from poison}
Primary_Bonuses {Primary bonuses}
Race {Race}
Reac_Adj_Cha {People's reaction}
Reac_Adj_Dex {Reaction}
Regeneration {Regeneration}
Resurrection_Survival {Chance to survive resurrection}
roll {Roll dices}
Spell_level {Maximum spell level}
Str  {Strength}
Sys_Shock {Chance to save from system shock}
Weight_Allow {Weight allowence}
Wis  {Wisdom}
}