::msgcat::mcmset ru {
Abilities {Способности}
back {Назад}
Bend_Bars {Шанс раздвинуть решётки}
Bonus_Spells_Lvl1 {Дополнительные заклятья уровня 1}
Bonus_Spells_Lvl2 {Дополнительные заклятья уровня 2}
Bonus_Spells_Lvl3 {Дополнительные заклятья уровня 3}
Bonus_Spells_Lvl4 {Дополнительные заклятья уровня 4}
Bonus_Spells_Lvl5 {Дополнительные заклятья уровня 5}
Bonus_Spells_Lvl6 {Дополнительные заклятья уровня 6}
Bonus_Spells_Lvl7 {Дополнительные заклятья уровня 7}
Ch_To_Fail_Spell {Шанс ненаколдовать заклятье}
Ch_To_Lrn_Spell {Шанс выучить заклятье}
Cha  {Харизма}
changes_after_restart {Изменения будут применены после перезагрузки программы.}
Con  {Телосложение}
copy {Копировать}
create {Создать}
cut {Вырезать}
Def_Adj {Модификатор защиты}
delete {Удалить}
Dex {Ловкость}
Dmg_Adj {Модификатор урона}
exit {Выход}
female {Женский}
file {Файл}
forward {Вперёд}
Gender {Пол}
Illusion_Immunity {Защита от иллюзий}
Int  {Интеллект}
help {Помощь}
hero {Герой}
heroes {Герои}
Hit_Prob {Шанс удара}
HP_Adj {Модификатор здоровья}
language {Язык}
Loyality_Base {Базовая лояльность слуг}
Magic_Save {Шанс защиты от магии}
Magical_Def_Adj {Модификатор магической защиты}
main_title {Помощник ролевика}
male {Мужской}
Max_Press {Максимальное допустимое давление}
Max_Spells_Lvl {Максимальный уровень заклятий}
Max_Henchmen {Максимальное кол-во слуг}
Missile_Atc_Adj {Модификатор защиты от стрел}
Name {Имя}
Num_Of_Lang {Максимальное кол-во языков}
open {Открыть}
Open_Doors {Шанс взломать дверь}
open_file_with {Открыть файл с...}
Open_Special_Doors {Шанс открыть специальную дверь}
paste {Вставить}
Poison_Save {Шанс защиты от яда}
Primary_Bonuses {Основные бонусы}
Race {Раса}
Reac_Adj_Cha {Модификатор реакции окружающих}
Reac_Adj_Dex {Реакция персонажа}
Regeneration {Регенерация}
Resurrection_Survival {Шанс пережить воскрешение}
roll {Бросить кубики}
Spell_level {Уровень заклятий}
Str {Сила}
Sys_Shock {Шанс пережить шок}
Weight_Allow {Максимальный носимый вес}
Wis {Мудрость}
}